import{a as v,S as M,i as c}from"./assets/vendor-C3hA4BqS.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))s(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function a(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(r){if(r.ep)return;r.ep=!0;const o=a(r);fetch(r.href,o)}})();const q="55695141-df1ad6569c10fb966400a1286",E="https://pixabay.com/api/";async function y(e,t=1){const a={key:q,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};return(await v.get(E,{params:a})).data}const P=new M(".gallery a",{captionsData:"alt",captionDelay:250});function $(e){return e.map(({webformatURL:t,largeImageURL:a,tags:s,likes:r,views:o,comments:i,downloads:S})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${a}">
        <img class="gallery-image" src="${t}" alt="${s}" loading="lazy" />
        <div class="info">
          <p class="info-item"><b>Likes</b><span>${r}</span></p>
          <p class="info-item"><b>Views</b><span>${o}</span></p>
          <p class="info-item"><b>Comments</b><span>${i}</span></p>
          <p class="info-item"><b>Downloads</b><span>${S}</span></p>
        </div>
      </a>
    </li>`).join("")}function m(e,t,a=!1){const s=$(t);a?e.insertAdjacentHTML("beforeend",s):e.innerHTML=s,P.refresh()}function B(e){e.innerHTML=""}function g(e){e.style.display="block"}function h(e){e.style.display="none"}function b(e){e.style.display="block"}function l(e){e.style.display="none"}const L=document.querySelector(".form"),p=document.querySelector(".gallery"),n=document.querySelector(".load-more"),f=document.querySelector(".loader-container");let u=1,d="";const w=15;L.addEventListener("submit",O);n.addEventListener("click",H);async function O(e){if(e.preventDefault(),d=e.currentTarget.elements.searchQuery.value.trim(),!!d){u=1,B(p),l(n),g(f);try{const t=await y(d,u);if(t.hits.length===0){c.error({message:"Sorry, there are no images matching your search query."}),l(n);return}m(p,t.hits),t.totalHits<=w?(l(n),c.info({message:"We're sorry, but you've reached the end of search results."})):b(n)}catch{c.error({message:"Error fetching images!"})}finally{h(f),L.reset()}}}async function H(){u+=1,l(n),g(f);try{const e=await y(d,u);m(p,e.hits,!0);const t=document.querySelector(".gallery-item");if(t){const{height:s}=t.getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"})}const a=Math.ceil(e.totalHits/w);u>=a?(l(n),c.info({message:"We're sorry, but you've reached the end of search results."})):b(n)}catch{c.error({message:"Error loading more images!"})}finally{h(f)}}
//# sourceMappingURL=index.js.map
