import{a as v,S as M,i as c}from"./assets/vendor-C3hA4BqS.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function a(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=a(t);fetch(t.href,o)}})();const P="55695141-df1ad6569c10fb966400a1286",$="https://pixabay.com/api/";async function y(e,r=1){const a={key:P,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15};return(await v.get($,{params:a})).data}let B=new M(".gallery a",{captionsData:"alt",captionDelay:250});function m(e){return e.map(({webformatURL:r,largeImageURL:a,tags:s,likes:t,views:o,comments:i,downloads:q})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${a}">
        <img class="gallery-image" src="${r}" alt="${s}" loading="lazy" />
        <div class="info">
          <p class="info-item"><b>Likes</b><span>${t}</span></p>
          <p class="info-item"><b>Views</b><span>${o}</span></p>
          <p class="info-item"><b>Comments</b><span>${i}</span></p>
          <p class="info-item")<b>Downloads</b><span>${q}</span></p>
        </div>
      </a>
    </li>`).join("")}function E(e){e.innerHTML=""}function g(e){e.style.display="block"}function h(e){e.style.display="none"}function b(e){e.style.display="block"}function f(e){e.style.display="none"}function L(){B.refresh()}function O(){const e=document.querySelector(".gallery-item");if(e){const{height:r}=e.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}}const w=document.querySelector(".form"),p=document.querySelector(".gallery"),n=document.querySelector(".load-more"),d=document.querySelector(".loader-container");let l=1,u="";const S=15;w.addEventListener("submit",x);n.addEventListener("click",H);async function x(e){if(e.preventDefault(),u=e.currentTarget.elements.searchQuery.value.trim(),!u){c.warning({message:"Please enter a search query"});return}l=1,E(p),f(n),g(d);try{const r=await y(u,l);if(r.hits.length===0){c.error({message:"Sorry, there are no images matching your search query."});return}p.innerHTML=m(r.hits),L(),r.totalHits>S&&b(n)}catch{c.error({message:"Something went wrong!"})}finally{h(d),w.reset()}}async function H(){l+=1,f(n),g(d);try{const e=await y(u,l);p.insertAdjacentHTML("beforeend",m(e.hits)),L(),O();const r=Math.ceil(e.totalHits/S);l>=r?(f(n),c.info({message:"We're sorry, but you've reached the end of search results."})):b(n)}catch{c.error({message:"Error loading more images!"})}finally{h(d)}}
//# sourceMappingURL=index.js.map
